### ISSUE TITLE
Unable to update fields in User model

### ISSUE THREAD

**Issue by rvigneshw** [rezaamini-ir/laravel-easypanel#10]
When I try to update no error is being shown, but still the field value not getting updated.

**Comment by rezaamini-ir** [comment]
Could you please show me the update form with a screenshot?

**Comment by rvigneshw** [comment]
![image](https://user-images.githubusercontent.com/22572374/109935335-7d899d80-7cf3-11eb-8b64-147c05bb20a1.png)
When I try to update credits to some value it doesn't update in DB, also no error is being shown

**Comment by rvigneshw** [comment]
![image](https://user-images.githubusercontent.com/22572374/109935551-ba559480-7cf3-11eb-878f-17c83e39b580.png)
When I update the credits field, it doesn't reflect in DB

**Comment by rvigneshw** [comment]
I've fixed it, You need to remove 
`            'user_id' => auth()->id(),` 
from Update.php

**Comment by rezaamini-ir** [comment]
You could manage it in your crud config
`with_auth` key
