### ISSUE TITLE
ErrorException: Trying to get property 'id' of non-object

### ISSUE THREAD

**Issue by Mokei-it** [rezaamini-ir/laravel-easypanel#13]
Hello there,

going to http://localhost:8000/admin before login I get:

ErrorException
Trying to get property 'id' of non-object

at line 13 in file \vendor\rezaamini-ir\laravel-easypanel\src\Http\Middleware\isAdmin.php

Thank you

**Comment by rezaamini-ir** [comment]
It's because you need to login as an user and you have not!

**Comment by rezaamini-ir** [comment]
It's because you need to login as an user and you have not!

**Comment by Mokei-it** [comment]
Hello,
let me explain better.
If you try to go directly to http://localhost:8000/admin before login, you get an ErrorException.

To get a better answer from server what do you think to modify \vendor\rezaamini-ir\laravel-easypanel\src\Http\Middleware\isAdmin.php

from
    public function handle($request, Closure $next)
    {
		if(!AuthFacade::checkIsAdmin(auth()->user()->id)){
				return redirect(config('easy_panel.redirect_unauthorized'));
		}
        return $next($request);
    }


to
    public function handle($request, Closure $next)
    {
		if(!Auth::check()) {
			return redirect('login');
		}else{
			if(!AuthFacade::checkIsAdmin(auth()->user()->id)){
				return redirect(config('easy_panel.redirect_unauthorized'));
			}
		}
        return $next($request);
    }
