### ISSUE TITLE
add_is_superuser_column_to_users_table

### ISSUE THREAD

**Issue by Mokei-it** [rezaamini-ir/laravel-easypanel#14]
Hello,
maybe somebody is interested in the following migration file:
2021_04_06_000000_add_is_superuser_column_to_users_table.php

`<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class AddIsSuperuserColumnToUsersTable extends Migration
{

    public function up()
    {
        Schema::table('users', function (Blueprint $table) {
            $table->boolean('is_superuser')
                    ->after('remember_token')
                    ->nullable();
        });
    }

    public function down()
    {
        Schema::table('users', function (Blueprint $table) {
            $table->dropColumn('is_superuser');
        });
    }
}
`

**Comment by rezaamini-ir** [comment]
We didn't add this migration because everybody can change the column name in configuration based on their database structure
