### ISSUE TITLE
I could not create new crud

### ISSUE THREAD

**Issue by shankar-bavan** [rezaamini-ir/laravel-easypanel#19]
I got same issue.
laravel/framework: "^7.24",
rezaamini-ir/laravel-easypanel: "^1.5",

```
php artisan panel:config User

BadMethodCallException 

Method EasyPanel\Commands\Actions\MakeCRUDConfig::qualifyModel does not exist.

at vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:103
```

_Originally posted by @shankar-bavan in https://github.com/rezaamini-ir/laravel-easypanel/issues/11#issuecomment-847569771_

**Comment by rezaamini-ir** [comment]
Thanks for your report!
I will check it and relaese a force version as fast as possible.

**Comment by rezaamini-ir** [comment]
A new version was released.
Could you please update Easypanel then tell the result?

**Comment by rezaamini-ir** [comment]
@shankar-bavan A new version was released.
Could you please update Easypanel then tell the result?

**Comment by shankar-bavan** [comment]
@rezaamini-ir Thank you for the update
It is working for this command

`php artisan panel:config User`

same error for below command

`php artisan panel:crud use`

``` BadMethodCallException 

  Method EasyPanel\Commands\CRUDActions\MakeCreate::qualifyModel does not exist.

  at vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:103
     99|      */
    100|     public function __call($method, $parameters)
    101|     {
    102|         if (! static::hasMacro($method)) {
  > 103|             throw new BadMethodCallException(sprintf(
    104|                 'Method %s::%s does not exist.', static::class, $method
    105|             ));
    106|         }
    107| 

  • Bad Method Call: Did you mean EasyPanel\Commands\CRUDActions\MakeCreate::qualifyClass() ? 


```

**Comment by rezaamini-ir** [comment]
@shankar-bavan It was fixed in the new release.
Update Easypanel to 1.5.4 version.

Thanks for your report!
I guess the `qualifyModel` method has been added from one of the Laravel 7 versions.

**Comment by shankar-bavan** [comment]
@rezaamini-ir 
I updated. I think changes not merged with master?

**Comment by rezaamini-ir** [comment]
Use the below command:
```
composer require rezaamini-ir/laravel-easypanel --no-cache
```

**Comment by shankar-bavan** [comment]
I got this error

`Class 'EasyPanel\Commands\CRUDActions\Str' not found`

**Comment by rezaamini-ir** [comment]
Was fixed.
Retry the composer command.

**Comment by shankar-bavan** [comment]
one more question.
I could not able to run `php artisan route:cache` after install this package
Is this fixable ?
```
LogicException 

  Unable to prepare route [admin/logout] for serialization. Uses Closure
```

**Comment by rezaamini-ir** [comment]
It will be fixed soon in the new release.

**Comment by shankar-bavan** [comment]
@rezaamini-ir 
when I run this command, application got stuck and after few min, I got `Killed` message

` php artisan panel:crud user`

**Comment by shankar-bavan** [comment]
> @rezaamini-ir
> when I run this command, application got stuck and after few min, I got `Killed` message
> 
> ` php artisan panel:crud user`

@rezaamini-ir any solution for this?

**Comment by rezaamini-ir** [comment]
Please add some attachment.

**Comment by shankar-bavan** [comment]
@rezaamini-ir 
after run this command, laprtop frozen for 3 second and got killed message

![image](https://user-images.githubusercontent.com/48729909/119930659-780fbc80-bf9d-11eb-9b87-8f28b40e484c.png)

**Comment by rezaamini-ir** [comment]
@shankar-bavan Do you have this problem just with this command?
What's your OS?

**Comment by shankar-bavan** [comment]
@rezaamini-ir 
yes. only with this command. I use ubuntu

I'm using easypanel with Larave 8 project without any issues.
I got this issue only with Laravel 7 project.

**Comment by rezaamini-ir** [comment]
Does it same for all of the CRUD configs in Laravel 7 or just it appears for one CRUD setting?

**Comment by shankar-bavan** [comment]
it is coming for php artisan panel:crud

**Comment by rezaamini-ir** [comment]
@shankar-bavan 
What if you use `-f` flag?
What does your CRUD config file contain?

**Comment by shankar-bavan** [comment]
I tried with -f. same issue
config file is default content. 
currently I removed from laravel 7 project. I decided to use it with only laravel 8

Thank you again for your support :)
