### ISSUE TITLE
crud not working why?

### ISSUE THREAD

**Issue by anwar-moj** [rezaamini-ir/laravel-easypanel#20]
in config file esay_panel
```
'actions' => [
        'product'
    ],
```
 

`php artisan panel:crud product`
 There is no product in config file

**Comment by anwar-moj** [comment]
The problem was resolved by executing this command: 
`php artisan optimize: clear`

**Comment by rezaamini-ir** [comment]
Could you please add some attachments?

**Comment by baselrabia** [comment]
I had the same issue 
it is just an empty project with laravel 8 and I'm trying the package but I find this error, should I do something to register this config, or why does this error appears
![qqqq](https://user-images.githubusercontent.com/27627958/125839850-791bddc4-10c7-492d-8f1c-79bf3d33546a.PNG)

**Comment by baselrabia** [comment]
it worked, it happens because the actions in easypanel config is empty 

I should put the model name to be registered

```
// config/easy_panel.php
// enabled actions, If you want to create crud you must put action name here
    'actions' => ['post'],
```

**Comment by rezaamini-ir** [comment]
@baselrabia 
Yes, this error appears when you don't put crud file name in the config file.
