### ISSUE TITLE
Little grammatical errors

### ISSUE THREAD

**Issue by Mokei-it** [rezaamini-ir/laravel-easypanel#21]
In resources/cruds/[model].php please correct the following comments:
from
// searchable fields, if you dont want search feature, remove it
to
// searchable fields, if you don't want search feature, remove it

from
// which kind of data should be showed in list page
to 
// which kind of data should be shown in list page

Thank you!!

**Comment by rezaamini-ir** [comment]
Thanks!
You could open PR, anyway thanks!
