### ISSUE TITLE
Route /admin Not Found

### ISSUE THREAD

**Issue by hamidreza2005** [rezaamini-ir/laravel-easypanel#22]
I have installed panel and crud . i also defined the admin but when i go to  `/admin` it  says Not Found . Why?
i also ran `php artisan route:list` command but there was no additional routes

**Comment by rezaamini-ir** [comment]
Hello
Do `panel:` commands work?

**Comment by hamidreza2005** [comment]
> Hello
> Do `panel:` commands work?

Yes . they work

**Comment by hamidreza2005** [comment]
I added routes.php to RouteServiceProvider and also cleaned the cache and it works
