### ISSUE TITLE
گیج کننده

### ISSUE THREAD

**Issue by Mohammadreza-73** [rezaamini-ir/laravel-easypanel#27]
سلام
برای یه کاربر تازه کار گیج کننده س
من نصب کردم، بعد رفتم دستی تو دیتابیس به جدول `users` یک ستون اضافه کردم، بعد رفتم دوباره دستی یه کاربر ادمین insert کردم که بیام با اون کامند بگم که آقا این ادمین هستش!
چرا اینجوریه!؟ 😕
بقیه ادمین پنل های لاراول هم همینجوریه؟

**Comment by rezaamini-ir** [comment]
سلام، روزتون بخیر
پروسه شناسایی ادمین به این شکله بله
احتمالا بزودی لاگین و .. رو هم به پنل اضافه کنیم که نیاز به لاگین دستی نباشه
شما ایده بهتری دارید ؟

**Comment by Mohammadreza-73** [comment]
ممنون که پاسخ دادید.
راستش من تازه کارم و صاحب نظر نیستم.
فقط دنبال یادگیری هستم.

امیدوارم موفق باشید 🌹
