### ISSUE TITLE
Model in cruds/article.php 

### ISSUE THREAD

**Issue by Tony-The-Developer** [rezaamini-ir/laravel-easypanel#3]
Hello do we have to make the model 
    'model' => \App\Models\Article::class,
or is it supposed to auto-generate? Because I am getting.
Error
Class "App\Models\Article" not found

**Comment by rezaamini-ir** [comment]
Hello Tony.
It's a just example of crud file and you should make your own CRUD config
file and delete this.
You can delete this and make a crud config for your model with
"php artisan panel:config name -m ModelName"

‫‪Tony Ashvanian‬‏ <‪notifications@github.com‬‏> در تاریخ سه‌شنبه ۲۶
ژانویهٔ ۲۰۲۱ ساعت ۲۳:۰۵ نوشت:‬
