### ISSUE TITLE
WORK ON LOCAL BUT NOT ONLINE ! What To Do

### ISSUE THREAD

**Issue by DKRDev** [rezaamini-ir/laravel-easypanel#30]
The package works fine when i'm on my local machine but as soon I upload it in my CPanel it show's this error.
FIRST PICTURE LOCAL WORKS FINE

<img width="945" alt="easy1" src="https://user-images.githubusercontent.com/53798944/134809378-6719aa6b-1b86-4c02-8f10-2eaa450a4973.PNG">

SECOND ONE CPANEL
<img width="815" alt="easy2" src="https://user-images.githubusercontent.com/53798944/134809419-a98c47be-4379-4b8a-b253-f852020f0cf1.PNG">

**Comment by rezaamini-ir** [comment]
This error returns when there is a problem with your class namespace or the file doesn't exist.
Check out that you have this class with the correct namespace or maybe there is a problem with your composer to load the right namespcae.
