### ISSUE TITLE
@tnatanael, I thaught the same, untill I manually added a `is_superuser` column to my users-table (type `int` with length 1). This isn't done by migrations.

### ISSUE THREAD

**Issue by zachary** [rezaamini-ir/laravel-easypanel#31]
Still doesn't work, no admin route shown.

@tnatanael, I thaught the same, untill I manually added a `is_superuser` column to my users-table (type `int` with length 1). This isn't done by migrations.
I tried the `php artisan panel:add [user_id]` command but this didn't work for me, so I manually changed the `is_superuser` to value `1`, then /admin works.

Steps from scratch:
1. composer global require laravel/installer
2. laravel new [project-folder-name] --jet
3. cd [project-folder-name]
4. composer require rezaamini-ir/laravel-easypanel
5. php artisan panel:install
6. Create database + user and update credentials in `.env`
7. php artisan migrate
8. npm install && npm run dev
9. Register a new user using /register
10. Manually add an is_superuser-column to your users-table and set value to '1' for your user.
11. Go to /admin and see if it works.
12. Bonus: update `config/easy_panel.php` and set `todo` to `true`

__Originally posted by @J87NL in https://github.com/rezaamini-ir/laravel-easypanel/issues/4#issuecomment-782829132__

**Comment by rezaamini-ir** [comment]
Is there any admin panel route when you execute `route:list` command?
