### ISSUE TITLE
Error in create crud process

### ISSUE THREAD

**Issue by luckyboy1001** [rezaamini-ir/laravel-easypanel#38]
I have just installed the latest version of the package and got this error when creating crud

 ErrorException 

Trying to get property 'route' of non-object

at vendor/rezaamini-ir/laravel-easypanel/src/Parsers/StubParser.php:202
  198▕             '{{ modelName }}' => ucfirst($modelName),
  199▕             '{{ data }}' => $this->parseDataInBlade(),
  200▕             '{{ titles }}' => $this->parseTitlesInBlade(),
  201▕             '{{ inputs }}' => $this->parseInputsInBlade(),
➜ 202▕             '{{ routeName }}' => crud(strtolower($modelName))->route,
  203▕         ];
  204▕ 
  205▕         $this->setLocaleTexts();
  206▕ 

    +28 vendor frames 
29  artisan:37
    Illuminate\Foundation\Console\Kernel::handle()

The steps I passed

1. install package
2. add admin user
3. create config file for Post model :: `php artisan panel:config Post`
and get this result
    **Post config file was created for Post model
    You can manage it in : app/CRUD/PostComponent.php**
4. php artisan panel:crud Post and then got the error

I think the documention is not clear and actually complete, and it makes using the package hard.

**Comment by rezaamini-ir** [comment]
@luckyboy1001 Hi,
Please use GUI to create CRUD which is available on admin page.

**Comment by luckyboy1001** [comment]
I have tried it but got this error

Symfony\Component\Routing\Exception\RouteNotFoundException
Route [admin.user.read] not defined. (View: /home/mohammad/Desktop/open-source-projects/laravel-easy-panel/laravel-app/resources/views/vendor/admin/livewire/crud/create.blade.php)

**Comment by rezaamini-ir** [comment]
First of all, uninstall the package completely with `panel:uninstall` command then clear the `cruds` table.
then you can re-execute `panel:install` command.

**Comment by luckyboy1001** [comment]
I have even created a new laravel project but get the same error 
Symfony\Component\Routing\Exception\RouteNotFoundException
Route [admin.user.read] not defined. (View: /home/mohammad/Desktop/open-source-projects/laravel-easy-panel/laravel-app/resources/views/vendor/admin/livewire/crud/create.blade.php)

Could it not be compatible with Laravel latest version?

**Comment by rezaamini-ir** [comment]
No, there was a problem with `create page` which was fixed.
Please update the package to `1.8.1` version with composer, then check it out.
