### ISSUE TITLE
Some file are missing

### ISSUE THREAD

**Issue by webtasty** [rezaamini-ir/laravel-easypanel#39]
Hi, 
I'm trying to install the package but some errors occurs, i've `laravel/framework ^8.65`, `rezaamini-ir/laravel-easypanel ^1.8`, breeze for login manager and below all step executed:

```sh
composer require laravel/laravel laravel-easypanel.dev.local
composer require laravel/breeze --dev
php artisan breeze:install
npm install && npm run dev
composer require rezaamini-ir/laravel-easypanel
```

Here i've created sqlite db, added `is_superuser` type boolean on user migration, create a seed wirth only one user as admin, next steps:

```sh
php artisan panel:install
php artisan migrate:fresh --seed
php artisan panel:add 1
```

I see the panel when i go to `/admin`, but if i try to create CRUDs from panel and i've got an error

![Route  admin user read  not defined (View C Users Cutrone laragon www larvel-easypanel](https://user-images.githubusercontent.com/60032744/145364021-8a354201-f14e-4608-a66e-cc09e558761d.png)

So i try to perform crud from console and i run:

```sh
php artisan make:model -crfm Article
php artisan panel:config Article
```
This return message:

`Article config file was created for Article model`
`You can manage it in : app/CRUD/ArticleComponent.php and then run`

```sh
php artisan panel:crud article
```

but i've got this other error

![route_error](https://user-images.githubusercontent.com/60032744/145364063-cea77bb0-1238-49ce-ad2c-cc8272452064.PNG)

In other issue posted i've seen that the folder structure after package installation are bit different, in the `resource/view` folder i've only `vendor`, and i can't see the cruds for the user, the attachments below show up my folder structure after run all of the commands above.

![VScode_structure01](https://user-images.githubusercontent.com/60032744/145360874-58d991b9-c543-4332-9735-c5dad98e3f27.PNG)
![VScode_structure02](https://user-images.githubusercontent.com/60032744/145360873-f8c2b315-6068-4167-8e38-ef711121d8d5.PNG)
![VScode_structure03](https://user-images.githubusercontent.com/60032744/145360867-c9876a47-f83f-4d0a-a388-bb4e8891dc14.PNG)

And another thing is that if i try to run `php artisan panel:migration` and then i run `php artisan migrate` an then set `'todos' => true` to **config/easy_panel.php** i've got this

![SQLSTATE HY000  General error 1 no such table todos (SQL select count( ) as aggregate ](https://user-images.githubusercontent.com/60032744/145364101-85e5e34b-7c1a-4189-a873-c629805a342c.png)

What can i do for this?
Thank you!

**Comment by rezaamini-ir** [comment]
Do you use 1.8.1 version with GUI?

**Comment by webtasty** [comment]
No, i have the `1.8.0` installed, but if i try to add version constraint to `composer.json` to `1.8.1` i've got this error:
```Your requirements could not be resolved to an installable set of packages.```.

How can i update package?
Thanks.

**Comment by rezaamini-ir** [comment]
Something has a conflict with the new version.
Please add more detail of the error or re-install package with the new laravel project.

**Comment by webtasty** [comment]
I've tested on fresh laravel installation, i've tried to update package from command with `composer update rezaami-ir/laravel-easypanel:"^1.8.1"`

![commposer-update-laravel-easypanel](https://user-images.githubusercontent.com/60032744/145780452-9ea84755-da87-40a9-a9b7-d9e70a4e6313.PNG)

And i have add `^1.8.1` version constraint to `composer.json` and try to run `composer update`

![commposer-update-json-laravel-easypanel](https://user-images.githubusercontent.com/60032744/145780635-d7c7a007-c3c4-4922-9df5-09fce69c020c.PNG)

From both clear laravel and easypanel installation which command i should run for update package to 1.8.1?
Thank you

**Comment by rezaamini-ir** [comment]
Hmm, please try this command:
```
composer update rezaamini-ir/laravel-easypanel --no-cache
```

**Comment by webtasty** [comment]
Oh... great! 
Now it's work, but **only from GUI,** from shell cruds creation throw an exception, but now i can see the package, good!

Thanks for help!
