### ISSUE TITLE
In laravel 8 fresh installation it simpli does not work...

### ISSUE THREAD

**Issue by tnatanael** [rezaamini-ir/laravel-easypanel#4]
As the title, i tryed everything, offcourse something is missing in the tutorial...

**Comment by rezaamini-ir** [comment]
Could you please attach the error message as a photo?

**Comment by tnatanael** [comment]
No erros, the admin route simpli does not exists

**Comment by rezaamini-ir** [comment]
You mean you get 404 error?

**Comment by tnatanael** [comment]
Yes! 404 on /admin route

**Comment by rezaamini-ir** [comment]
I think your installation has been failed.
Because after registering Service Provider routes will be registered.
Remove the package with composer then reinstall it with `--no-cache` flag.

**Comment by tnatanael** [comment]
Same behavior here... 404 for /admin route.

I see no routes registered on routes/web.php is this expected?

![image](https://user-images.githubusercontent.com/11818318/107516917-d7cb8e80-6b8b-11eb-936e-56c19f2dc2e7.png)

**Comment by rezaamini-ir** [comment]
I said reinstall with composer not artisan command

`panel:install` install front end dependency and components

**Comment by tnatanael** [comment]
Sure ive done this too:
composer remove rezaamini-ir/laravel-easypanel
And:
composer require rezaamini-ir/laravel-easypanel --no-cache

**Comment by tnatanael** [comment]
> I said reinstall with composer not artisan command
> 
> `panel:install` install front end dependency and components
> first remove package:
> `composer remove rezaamini-ir/laravel-easypanel`
> then :
> `composer require rezaamini-ir/laravel-easypanel --no-cache`

Also done, same problem...

**Comment by rezaamini-ir** [comment]
Have you updated Laravel version?
Tell me your Laravel version

**Comment by tnatanael** [comment]
Laravel 8 default freah installation, latest version!

**Comment by rezaamini-ir** [comment]
I checked it and there was no problem.
You may have a conflict in your project with routes or service providers.

**Comment by J87NL** [comment]
@tnatanael, I thaught the same, untill I manually added a `is_superuser` column to my users-table (type `int` with length 1). This isn't done by migrations.
I tried the `php artisan panel:add [user_id]` command but this didn't work for me, so I manually changed the `is_superuser` to value `1`, then /admin works.

Steps from scratch:
1. composer global require laravel/installer
2. laravel new [project-folder-name] --jet
3. cd [project-folder-name]
4. composer require rezaamini-ir/laravel-easypanel
5. php artisan panel:install
6. Create database + user and update credentials in `.env`
7. php artisan migrate
8. npm install && npm run dev
9. Register a new user using /register
10. Manually add an is_superuser-column to your users-table and set value to '1' for your user.
11. Go to /admin and see if it works.
12. Bonus: update `config/easy_panel.php` and set `todo` to `true`

**Comment by rezaamini-ir** [comment]
@J87NL Thanks for your answer, I think some users don't add `is_superuser` to the User model as a fillable field and maybe It's because of tha!
