### ISSUE TITLE
File upload error - undefined variable $string

### ISSUE THREAD

**Issue by dftd** [rezaamini-ir/laravel-easypanel#42]
When uploading a image on my model with EasyPanel I get the following

`Undefined variable: string (View: resources/views/livewire/admin/user/create.blade.php)`

Here's that line of code

```
@if($image and !$errors->has('image') and $string instanceof \Livewire\TemporaryUploadedFile and (in_array( $image->guessExtension(), ['png', 'jpg', 'gif', 'jpeg'])))
    <a href="{{ $image->temporaryUrl() }}"><img width="200" height="200" class="img-fluid shadow" src="{{ $image->temporaryUrl() }}" alt=""></a>
@endif
```

Looks like `$string instanceof \Livewire\TemporaryUploadedFile` should be `$image instanceof \Livewire\TemporaryUploadedFile`.

**Comment by rezaamini-ir** [comment]
Please update package to `1.8.3` version using:
```
composer update rezaamini-ir/laravel-easypanel --no-cache
```
