### ISSUE TITLE
Passwords are stored in plain text

### ISSUE THREAD

**Issue by dftd** [rezaamini-ir/laravel-easypanel#43]
Using a field of type `password` stores the value in plain text.

The password should be hashed with default Laravel methods so we can use the panel to change passwords of users.

**Comment by dftd** [comment]
Can be resolved easily by replacing

`'password' => $this->password`

in Create.php/Update.php

with

`'password' => Hash::make($this->password)` (also include `use Illuminate\Support\Facades\Hash;`)

but it will get overwritten if you rebuild the CRUD.

**Comment by rezaamini-ir** [comment]
Thanks for your report, for now, we don't have any plan to make passwords hashed or anything.
But in the future, we will make some conditions to not re-generate all CRUDs.
But you can create a middleware and hash the password or you can use listen on `updating` event in model or also you can use `setPasswordAttribute` in your model.

There are tons of ways!

Do you have another idea?

**Comment by dftd** [comment]
Okay, thanks. I didn't put much thought in it, I just edited the generated files to do what I need. Hashing password on save and not showing the value when you're updating the model.
