### ISSUE TITLE
This problem has been fixed in 1.8.0 version.

### ISSUE THREAD

**Issue by Kirad20** [rezaamini-ir/laravel-easypanel#46]
I have the same problem in the 1.9 version

_Originally posted by @rezaamini-ir in https://github.com/rezaamini-ir/laravel-easypanel/issues/34#issuecomment-981108476_

**Comment by rezaamini-ir** [comment]
Do your namespaces in CRUD directory start with lowercase texts?

**Comment by Kirad20** [comment]
no
![image](https://user-images.githubusercontent.com/66331134/154306344-2c5e9b40-7576-476d-96a5-96d55f817e6f.png)
![image](https://user-images.githubusercontent.com/66331134/154306439-7267c2e4-a372-433b-99a5-3f2a4b219cb1.png)
![image](https://user-images.githubusercontent.com/66331134/154306526-78276c87-4f53-4f1f-be40-49e5820db6a9.png)
![image](https://user-images.githubusercontent.com/66331134/154306610-d0e00412-1b78-488b-94d1-26619c64807d.png)

**Comment by rezaamini-ir** [comment]
Do you change the namespace yourself?
It looks like your model name is `PetBreed` and your Component is `PetMedia` and this is why it throws an exception.

**Comment by rezaamini-ir** [comment]
https://github.com/rezaamini-ir/laravel-easypanel/issues/52#issuecomment-1115849649
