### ISSUE TITLE
Works Great!

### ISSUE THREAD

**Issue by Mroesger** [rezaamini-ir/laravel-easypanel#5]
Thanks for the plugin. Any thoughts on supporting more input fields like checkbox for Boolean?
Also any thoughts on supporting relationships between models?

![image](https://user-images.githubusercontent.com/12199349/107432461-d8f1b280-6adc-11eb-90fe-6b140d059e53.png)
![image](https://user-images.githubusercontent.com/12199349/107432491-e73fce80-6adc-11eb-821d-15f528639626.png)

**Comment by rezaamini-ir** [comment]
Thank for your opinion.
I have some plans to do these.
Feel free to Pull request and add new features :)
