### ISSUE TITLE
ERROR CLASS WITH \APP\CRUD\AIRESULTCOMPONENT NAMESPACE DOESN'T EXIST

### ISSUE THREAD

**Issue by gholamrezaeipt** [rezaamini-ir/laravel-easypanel#52]
Hi

Like #34 or #46 i have this error.

My model name is: AiResult
Generated component is AiResultCOMPONENT

How to Fix it?

**Comment by rezaamini-ir** [comment]
Hello, could you please tell me what version of EasyPanel you are using?

**Comment by rezaamini-ir** [comment]
This problem got fixed in `1.9.42` version.
Try to update the package using:
```bash
composer update rezaamini-ir/laravel-easypanel --no-cache
```
