### ISSUE TITLE
Model option should be valid and model should be exist

### ISSUE THREAD

**Issue by mgrWetales** [rezaamini-ir/laravel-easypanel#6]
I am getting the below error while trying to create panel config. Below is the first command I am using after installation.

sail artisan panel:config user -m user

Model option should be valid and model should be exist

**Comment by rezaamini-ir** [comment]
Hello
For now, You have to use this command style:
`sail artisan panel:config user -m User`
the model name should start with the first character of capitalized string

**Comment by mgrWetales** [comment]
Yes, it works. thanks
