### ISSUE TITLE
hi, a had problem on laravel 9 when generate autoload

### ISSUE THREAD

**Issue by k0d0k** [rezaamini-ir/laravel-easypanel#63]
this mya problem

Class EasyPanel\Http\Livewire\Role\Create located in E:/xampp/htdocs/test/laraku/vendor/rezaamini-ir/laravel-easypanel/src\Http\Livewire\Admins\Create.php does not comply with psr-4 autoloading standard. Skipping.

please advise

**Comment by ashek1412** [comment]
I am facing the problem

**Comment by rezaamini-ir** [comment]
Fixed in tag 2.1.3, thanks!
