### ISSUE TITLE
error when i want make crud 

### ISSUE THREAD

**Issue by HoseinSatari** [rezaamini-ir/laravel-easypanel#64]
درود و تشکر بابت پنل کاربردیتون ، من اول panel:config رو اجرا کردم و برای یکی از مدل هام کانفیگ رو ست کردم و بعدش دستور panel:crud رو اجرا گرفتم اما ارور null بودن route در صفحه vendor\rezaamini-ir\laravel-easypanel\src\Parsers\StubParser.php:197
 دریافت کردم این ارور بابت چیه و چطور میتونم رفعش کنم ؟
مورد بعدی که خواستم مطرح کنم ست کردن فایل منیجر بود پنل رو من هنوز کامل برسی نکردم اما طبق داکیومنتی که خوندم انگاری برای اپلود فایل از فایل منیجر استفاده نشده خواستم پیشنهاد بدم بصورت دیفالت یا حدعقل یک ماژول انتخاب این مورد رو به پکیج اضاف کنید ، 
https://github.com/UniSharp/laravel-filemanager

**Comment by HoseinSatari** [comment]
و اینکه ست کردن کامپوننت های لایو وایر به روت اتومات انجام میشه یا باید کاری در قبال این قضیه انجام داد ؟؟؟

**Comment by rezaamini-ir** [comment]
سلام وقتتون بخیر
نیازی به اجرای این کامند ها نیست
توی نسخه جدید فقط کافیه panel:install رو بزنید و بعدش دیگه یک محیط GUI در روت /admin دارید که اونجا میتونید از پکیج استفاده کنید و درست نیست کامند هارو الان دستی ران کنید برای ساخت این مسائل
