### ISSUE TITLE
Files are not being generated properly

### ISSUE THREAD

**Issue by mgrWetales** [rezaamini-ir/laravel-easypanel#7]
After crud generation files are not being generated properly. Controllers are showing on the root with names like below.

	"App\\Http\\Livewire\\Admin\\Article\\Create.php"
	"App\\Http\\Livewire\\Admin\\Article\\Read.php"
	"App\\Http\\Livewire\\Admin\\Article\\Single.php"
	"App\\Http\\Livewire\\Admin\\Article\\Update.php"
	"App\\Http\\Livewire\\Admin\\User\\Create.php"
	"App\\Http\\Livewire\\Admin\\User\\Read.php"
	"App\\Http\\Livewire\\Admin\\User\\Single.php"
	"App\\Http\\Livewire\\Admin\\User\\Update.php"
![Screenshot from 2021-02-18 14-40-29](https://user-images.githubusercontent.com/75842550/108334101-9e33fc80-71f7-11eb-86e6-863d515aa249.png)

I am using EasyPanel with Laravel Framework 8.27.0 and installed Jetstream with livewire as well.

**Comment by rezaamini-ir** [comment]
Could you please give me a screenshot of your directory structure?

**Comment by mgrWetales** [comment]
I am using a 
![Screenshot from 2021-02-18 15-07-28](https://user-images.githubusercontent.com/75842550/108337421-1a7c0f00-71fb-11eb-9e4a-21534984569c.png)
[directory-structure.txt](https://github.com/rezaamini-ir/laravel-easypanel/files/6001742/directory-structure.txt)

docker container.

**Comment by rezaamini-ir** [comment]
I guess it's because of your coding production and Directory separator.
I pushed a force release with 1.3.3 tag.
Reinstall package with `--no-cache` flag in composer then remove files and try this version out .

**Comment by mgrWetales** [comment]
It worked but only the controller got generated, views, routes, and other things didn't happen.

Also, the user is not being converted to admin with the flag is_superuser in the user's table. Command-line showing it's done.

![Screenshot from 2021-02-18 15-33-31](https://user-images.githubusercontent.com/75842550/108340543-b3f8f000-71fe-11eb-9435-4c687720d0b1.png)
![Screenshot from 2021-02-18 15-30-29](https://user-images.githubusercontent.com/75842550/108340554-b6f3e080-71fe-11eb-9536-76b1f2cc0f84.png)

**Comment by rezaamini-ir** [comment]
There two directories, "app" and "App" right?
please tell me about the information and structure of "App" directory, I think your OS care about capitalizied word

**Comment by mgrWetales** [comment]
Yes, right, I am using Ubuntu and it strictly case sensitive.
See screenshot:
![Screenshot from 2021-02-19 10-36-07](https://user-images.githubusercontent.com/75842550/108460439-b1e66e00-729e-11eb-9893-3453b9e5d037.png)

**Comment by rezaamini-ir** [comment]
You can update with --no-cache flag in the composer
this problem has been fixed.

**Comment by mgrWetales** [comment]
Yes, this problem has been fixed. 

Other issues are still there:

1. sail artisan panel:add [user_id] 
this command is not working, the is_superuser DB value is not changing to 1

2. When I made it manually and ran http://192.168.1.47/admin, got below error:
![image](https://user-images.githubusercontent.com/75842550/108490332-a90a9200-72c8-11eb-82b2-b3cf1e9b7f08.png)

3. I didn't run command for article but article views got generated:
![Screenshot from 2021-02-19 15-40-43](https://user-images.githubusercontent.com/75842550/108490635-f4bd3b80-72c8-11eb-9b70-767f2d1a346e.png)

**Comment by rezaamini-ir** [comment]
About `is_superuser` I have been working on this.
Because of `article` crud example, other 2 problems will be made.
I will remove this example in new version.
Do these steps:
1 - Remove `resources/cruds/article.php` 
2 - Remove `article` key in `config/easy_panel.php` in `actions` key.
3 - Run `sail artisan panel:crud -f`

**Comment by mgrWetales** [comment]
Wow, good job done bro, it worked. Thank you :)

Few more things I noticed:
1. My todo feature is false in the easy_panel.php but still todo directory got created under resources/views/vendor/admin/livewire/todo
![Screenshot from 2021-02-19 16-03-38](https://user-images.githubusercontent.com/75842550/108493557-7793c580-72cc-11eb-8ece-ce1b5f65ad68.png)
![Screenshot from 2021-02-19 16-03-19](https://user-images.githubusercontent.com/75842550/108493565-79f61f80-72cc-11eb-8f88-7b4f65ccb3c4.png)

2. Article views are still there under resources/views/livewire/admin/article
![Screenshot from 2021-02-19 16-08-07](https://user-images.githubusercontent.com/75842550/108493750-b0cc3580-72cc-11eb-80d8-c199fce9c80d.png)

3. Admin user should be redirected to the admin panel by default, for now, I am changing the URL and navigating to the admin panel.

**Comment by rezaamini-ir** [comment]
TODOs file should be generated anyway because you can run migrations and set TODOfeature as true and todo should be shown just with a refresh.
In the new release, we don't have article examples anymore.
Redirect automatically isn't a good choice, sometimes you don't want to see the admin panel and it's not a good action to redirect.
In the future, we will create new commands to delete actions and manage them better.

Thank you for your time that spends.

**Comment by mgrWetales** [comment]
Cool, I will be waiting for the update to make the user a superuser.

One more question :)
resources/views/vendor/admin/livewire/todo/
resources/views/livewire/admin/user/

Why todo view files are at a different location?

Can't we use one directory "admin" under the views folder to place layouts and other module views?
livewire & vendor/livewire folders are really required?

**Comment by rezaamini-ir** [comment]
Both of them are required.
Because of conflict with other packages, we put base files in different directories.
