### ISSUE TITLE
"Your requirements could not be resolved to an installable set of packages" Error

### ISSUE THREAD

**Issue by huseyin-lora** [rezaamini-ir/laravel-easypanel#70]
When I try to run the folowing command:
`composer require rezaamini-ir/laravel-easypanel --with-all-dependencies`,
I take the following output:
"
./composer.json has been updated
Running composer update rezaamini-ir/laravel-easypanel --with-all-dependencies
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - rezaamini-ir/laravel-easypanel[1.0.0, ..., 1.2.0] require php ^7.2.5 -> your php version (8.1.10) does not satisfy that requirement.
    - rezaamini-ir/laravel-easypanel[1.2.1, ..., 1.9.33] require illuminate/support ^6.0|^7.0|^8.0 -> found illuminate/support[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] **but these were not loaded, likely because it conflicts with another require.**
    - rezaamini-ir/laravel-easypanel[1.9.4, ..., 1.9.42, 2.0.0, ..., 2.1.0] require illuminate/support ^6.0|^7.0|^8.0|^9.0 -> found illuminate/support[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.15] **but these were not loaded, likely because it conflicts with another require.**
    - rezaamini-ir/laravel-easypanel[2.1.1, ..., 2.1.5] require illuminate/support ^7.0|^8.0|^9.0 -> found illuminate/support[v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.15] **but these were not loaded, likely because it conflicts with another require.**
    - rezaamini-ir/laravel-easypanel[2.2.0, ..., 2.2.1] require livewire/livewire ^1.0|^2.3 -> found livewire/livewire[v1.0.0, ..., v1.3.9, v2.3.0, ..., v2.12.6] but it conflicts with your root composer.json require (^3.0).
    - Root composer.json requires rezaamini-ir/laravel-easypanel * -> satisfiable by rezaamini-ir/laravel-easypanel[1.0.0, ..., 1.9.42, 2.0.0, ..., 2.2.1].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require rezaamini-ir/laravel-easypanel:*" to figure out if any version is installable, or "composer require rezaamini-ir/laravel-easypanel:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
"

After I run `npm update` and `composer update` I tried to run the same command or `composer require rezaamini-ir/laravel-easypanel:^2.0.0` command, but I did not work.

**Comment by oussamajad** [comment]
i got the same problem

**Comment by AfshinEfati** [comment]
same problem, PHP 8.2 and Laravel 10

**Comment by moaminsharifi** [comment]
The package currently only supports Livewire versions 1.0 and 2.3. However, other dependencies within your project require Livewire version 3.

```
- rezaamini-ir/laravel-easypanel[2.2.0, ..., 2.2.1] require livewire/livewire ^1.0|^2.3 -> found livewire/livewire[v1.0.0, ..., v1.3.9, v2.3.0, ..., v2.12.6] but it conflicts with your root composer.json require (^3.0).
- Root composer.json requires rezaamini-ir/laravel-easypanel * -> satisfiable by rezaamini-ir/laravel-easypanel[1.0.0, ..., 1.9.42, 2.0.0, ..., 2.2.1].
```

**Challenges:**
Adding support for Livewire version 3 while maintaining backward compatibility for users on older versions presents significant challenges.



**Proposals:**

- Fast Solution (Not Recommended):

> This suggestion to manually modify the package and its dependencies for Livewire 3 compatibility raises concerns

- Wait for Official Support:

> This approach prioritizes stability and avoids potential disruptions for current users.
