### ISSUE TITLE
Route [login] not defined.

### ISSUE THREAD

**Issue by MujahidHi5** [rezaamini-ir/laravel-easypanel#9]
![image](https://user-images.githubusercontent.com/63226807/109345258-ad6b1800-7891-11eb-8d24-53b5b3d17c37.png)

**Comment by rezaamini-ir** [comment]
Did you add the user as an admin?

**Comment by MujahidHi5** [comment]
No

**Comment by rezaamini-ir** [comment]
Please read this comment.
https://github.com/rezaamini-ir/laravel-easypanel/issues/4#issuecomment-782829132

**Comment by MujahidHi5** [comment]
Thanks
